name = "dimaslaut"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "c71a3087-98ec-4c99-98f7-0f95d6d56f64"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
